[package]
name = "communitea"
version = "0.1.0"
authors = ["Александр Втюрин <senior.joinu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/communitea/lib.rs"

[dependencies]
ic-cdk = "0.2.4"
ic-cdk-macros = "0.2.4"


